## These tests assume you have a DNN instance with DNN Community Forums installed and configured

## change values in http-client.env.json to match your environment / browser session

### first test is to verify a simple endpoint is reachable; we have a "Hello World" endpoint on each controller for this purpose"
### the HelloWorld endpoint does not require authentication but does require TabId and ModuleId headers for 'supported modules' check
GET {{hostname}}/API/ActiveForums/User/HelloWorld
TabId: {{tabid}}
ModuleId: {{moduleid}}


### test to get online users - requires authentication

GET {{hostname}}/API/ActiveForums/User/GetUsersOnline
TabId: {{tabid}}
ModuleId: {{moduleid}}
requestverificationtoken: {{requestverificationtoken}}

### test to update online users - requires authentication

POST {{hostname}}/API/ActiveForums/User/UpdateUserIsOnline
tabid: {{tabid}}
moduleid: {{moduleid}}
requestverificationtoken: {{requestverificationtoken}}
cookie: .DOTNETNUKE={{.DOTNETNUKE}};__RequestVerificationToken={{__RequestVerificationToken}}
